--- 
apiVersion: v1
kind: Namespace
metadata:
  name:  alxproj4

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: alxproj4
  name:  alxproj4-deploy
  labels:
    app:  ml-app 
spec:
  selector:
    matchLabels:
      app: ml-app 
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  ml-app  
    spec:
      containers:
      - name:  ml-app
        image:  70077007/alx-ml-app:latest
        ports:
        - containerPort:  80
          name:  http 
      restartPolicy: Always 

--- 
apiVersion: v1
kind: Service
metadata:
  name: alxproj4-svc
  namespace: alxproj4
spec:
  selector:
    app:  ml-app
  type: NodePort
  sessionAffinity: None 
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31031 

